# ============ language model configurations ============ 
# Set up OpenAI API key.
OPENAI_API_KEY="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"
# If you are using the API service provided by OpenAI, include the following line:
OPENAI_API_TYPE="openai"
# ============ retriever configurations ============
RETRIEVER = "searxng"
SEARXNG_API_KEY = "" 
SEARXNG_URL = "http://localhost:8087"
# ============ encoder configurations ============ 
ENCODER_API_TYPE="openai"